deploymentMode: "SelectorSyncSet"
selectorSyncSet:
  matchExpressions:
  - key: hive.openshift.io/version-major-minor
    operator: In
    values: ["4.5"]
  - key: hive.openshift.io/version-major-minor-patch
    operator: NotIn
    values: ["4.5.99"] # this should be replaced with the fixed version
