apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: osd-sre-admin
rules:
# SRE can get, list, and watch all resources
- apiGroups:
  - ""
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
# SRE can manage nodes
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - patch
# SRE can evict pods
- apiGroups:
  - ""
  resources:
  - pods/eviction
  verbs:
  - create
# SRE can delete jobs and builds
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - delete
  - deletecollection
- apiGroups:
  - build.openshift.io
  resources:
  - builds
  verbs:
  - delete
  - deletecollection
# SRE can manage projects
- apiGroups:
  - config.openshift.io
  resources:
  - projects
  verbs:
  - '*'
- apiGroups:
  - project.openshift.io
  resources:
  - projects
  verbs:
  - '*'
# SRE can review pod security policies
- apiGroups:
  - security.openshift.io
  resources:
  - podsecuritypolicyreviews
  - podsecuritypolicyselfsubjectreviews
  - podsecuritypolicysubjectreviews
  verbs:
  - create
# SRE can update existing groups
- apiGroups:
  - user.openshift.io
  resources:
  - groups
  verbs:
  - patch
  - update
# SRE can upgrade the cluster
- apiGroups:
  - config.openshift.io
  resources:
  - clusterversions
  verbs:
  - patch
  - update
# SRE can review RBAC policies (i.e. oc adm policy who-can ...)
- apiGroups:
  - authorization.openshift.io
  resources:
  - localresourceaccessreviews
  verbs:
  - create
# SRE can get and post to all endpoints
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
