apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: osd-sre-admin
rules:
- apiGroups:
  - ""
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - customresourcedefinitions
  - customresourcedefinitions/status
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - '*'
  verbs:
  - delete
  - deletecollection
- apiGroups:
  - apps.openshift.io
  resources:
  - '*'
  verbs:
  - delete
  - deletecollection
- apiGroups:
  - batch
  resources:
  - job
  - cronjob
  verbs:
  - delete
  - deletecollection
- apiGroups:
  - build.openshift.io
  resources:
  - buildconfigs
  - builds
  verbs:
  - delete
  - deletecollection
- apiGroups:
  - cloudcredential.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - config.openshift.io
  resources:
  - projects
  verbs:
  - '*'
- apiGroups:
  - hive.openshift.io
  resources:
  - clusterdeployments
  - selectorsyncidentityproviders
  - selectorsyncsets
  - syncidentityproviders
  - syncsets
  verbs:
  - '*'
- apiGroups:
  - operators.coreos.com
  resources:
  - subscriptions
  verbs:
  - '*'
- apiGroups:
  - policy
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - project.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - quota.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - '*'
- apiGroups:
  - security.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - storage.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - tuned.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - user.openshift.io
  resources:
  - groups
  verbs:
  - patch
  - update
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
