apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: osd-sre-admin
rules:
- apiGroups:
  - ""
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - admission.hive.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - apiregistration.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - apps.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - authentication.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - authorization.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - authorization.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - autoscaling
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - autoscaling.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - batch
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - build.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - certificates.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - cloudcredential.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - cluster.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - config.openshift.io
  resources:
  - apiservers
  verbs:
  - '*'
- apiGroups:
  - config.openshift.io
  resources:
  - authentications
  verbs:
  - '*'
- apiGroups:
  - config.openshift.io
  resources:
  - authentications/status
  verbs:
  - '*'
- apiGroups:
  - config.openshift.io
  resources:
  - builds
  verbs:
  - '*'
- apiGroups:
  - config.openshift.io
  resources:
  - clusteroperators
  verbs:
  - '*'
- apiGroups:
  - config.openshift.io
  resources:
  - clusteroperators/status
  verbs:
  - '*'
- apiGroups:
  - config.openshift.io
  resources:
  - clusterversions
  verbs:
  - '*'
- apiGroups:
  - config.openshift.io
  resources:
  - clusterversions/status
  verbs:
  - '*'
- apiGroups:
  - config.openshift.io
  resources:
  - consoles
  verbs:
  - '*'
- apiGroups:
  - config.openshift.io
  resources:
  - consoles/status
  verbs:
  - '*'
- apiGroups:
  - config.openshift.io
  resources:
  - dnses
  verbs:
  - '*'
- apiGroups:
  - config.openshift.io
  resources:
  - features
  verbs:
  - '*'
- apiGroups:
  - config.openshift.io
  resources:
  - images
  verbs:
  - '*'
- apiGroups:
  - config.openshift.io
  resources:
  - images/status
  verbs:
  - '*'
- apiGroups:
  - config.openshift.io
  resources:
  - infrastructures
  verbs:
  - '*'
- apiGroups:
  - config.openshift.io
  resources:
  - ingresses
  verbs:
  - '*'
- apiGroups:
  - config.openshift.io
  resources:
  - networks
  verbs:
  - '*'
- apiGroups:
  - config.openshift.io
  resources:
  - oauths
  verbs:
  # BLACKLIST: create
  # BLACKLIST: delete
  # BLACKLIST: deletecollection
   - get
   - list
  # BLACKLIST: patch
  # BLACKLIST: update
   - watch

- apiGroups:
  - config.openshift.io
  resources:
  - oauths/status
  verbs:
  - '*'
- apiGroups:
  - config.openshift.io
  resources:
  - projects
  verbs:
  - '*'
- apiGroups:
  - config.openshift.io
  resources:
  - registries
  verbs:
  - '*'
- apiGroups:
  - coordination.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - dns.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - events.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - extensions
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - healthchecking.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - hive.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - image.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - imageregistry.operator.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - ingress.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - k8s.cni.cncf.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - machineconfiguration.openshift.io
  resources:
  - containerruntimeconfigs
  verbs:
  - '*'
- apiGroups:
  - machineconfiguration.openshift.io
  resources:
  - containerruntimeconfigs/status
  verbs:
  - '*'
- apiGroups:
  - machineconfiguration.openshift.io
  resources:
  - controllerconfigs
  verbs:
  # BLACKLIST: create
  # BLACKLIST: delete
  # BLACKLIST: deletecollection
   - get
   - list
  # BLACKLIST: patch
  # BLACKLIST: update
   - watch

- apiGroups:
  - machineconfiguration.openshift.io
  resources:
  - controllerconfigs/status
  verbs:
  - '*'
- apiGroups:
  - machineconfiguration.openshift.io
  resources:
  - kubeletconfigs
  verbs:
  - '*'
- apiGroups:
  - machineconfiguration.openshift.io
  resources:
  - kubeletconfigs/status
  verbs:
  - '*'
- apiGroups:
  - machineconfiguration.openshift.io
  resources:
  - machineconfigpools
  verbs:
  # BLACKLIST: create
  # BLACKLIST: delete
  # BLACKLIST: deletecollection
   - get
   - list
  # BLACKLIST: patch
  # BLACKLIST: update
   - watch

- apiGroups:
  - machineconfiguration.openshift.io
  resources:
  - machineconfigpools/status
  verbs:
  - '*'
- apiGroups:
  - machineconfiguration.openshift.io
  resources:
  - machineconfigs
  verbs:
  # BLACKLIST: create
  # BLACKLIST: delete
  # BLACKLIST: deletecollection
   - get
   - list
  # BLACKLIST: patch
  # BLACKLIST: update
   - watch

- apiGroups:
  - machineconfiguration.openshift.io
  resources:
  - mcoconfigs
  verbs:
  - '*'
- apiGroups:
  - machine.openshift.io
  resources:
  - clusters
  verbs:
  - '*'
- apiGroups:
  - machine.openshift.io
  resources:
  - clusters/status
  verbs:
  - '*'
- apiGroups:
  - machine.openshift.io
  resources:
  - machineclasses
  verbs:
  # BLACKLIST: create
  # BLACKLIST: delete
  # BLACKLIST: deletecollection
   - get
   - list
  # BLACKLIST: patch
  # BLACKLIST: update
   - watch

- apiGroups:
  - machine.openshift.io
  resources:
  - machinedeployments
  verbs:
  - '*'
- apiGroups:
  - machine.openshift.io
  resources:
  - machinedeployments/scale
  verbs:
  - '*'
- apiGroups:
  - machine.openshift.io
  resources:
  - machinedeployments/status
  verbs:
  - '*'
- apiGroups:
  - machine.openshift.io
  resources:
  - machines
  verbs:
  # BLACKLIST: create
  # BLACKLIST: delete
  # BLACKLIST: deletecollection
   - get
   - list
  # BLACKLIST: patch
  # BLACKLIST: update
   - watch

- apiGroups:
  - machine.openshift.io
  resources:
  - machinesets
  verbs:
  # BLACKLIST: create
  # BLACKLIST: delete
  # BLACKLIST: deletecollection
   - get
   - list
  # BLACKLIST: patch
  # BLACKLIST: update
   - watch

- apiGroups:
  - machine.openshift.io
  resources:
  - machinesets/scale
  verbs:
  - '*'
- apiGroups:
  - machine.openshift.io
  resources:
  - machinesets/status
  verbs:
  - '*'
- apiGroups:
  - machine.openshift.io
  resources:
  - machines/status
  verbs:
  - '*'
- apiGroups:
  - marketplace.redhat.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - metrics.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - alertmanagers
  verbs:
  # BLACKLIST: create
  # BLACKLIST: delete
  # BLACKLIST: deletecollection
   - get
   - list
  # BLACKLIST: patch
  # BLACKLIST: update
   - watch

- apiGroups:
  - monitoring.coreos.com
  resources:
  - prometheuses
  verbs:
  # BLACKLIST: create
  # BLACKLIST: delete
  # BLACKLIST: deletecollection
   - get
   - list
  # BLACKLIST: patch
  # BLACKLIST: update
   - watch

- apiGroups:
  - monitoring.coreos.com
  resources:
  - prometheusrules
  verbs:
  # BLACKLIST: create
  # BLACKLIST: delete
  # BLACKLIST: deletecollection
   - get
   - list
  # BLACKLIST: patch
  # BLACKLIST: update
   - watch

- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - '*'
- apiGroups:
  - networking.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - network.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - networkoperator.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - oauth.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - operator.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - operators.coreos.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - operatorstatus.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - policy
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - project.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - quota.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  verbs:
  # BLACKLIST: create
  # BLACKLIST: delete
  # BLACKLIST: deletecollection
   - get
   - list
  # BLACKLIST: patch
  # BLACKLIST: update
   - watch

- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  # BLACKLIST: create
  # BLACKLIST: delete
  # BLACKLIST: deletecollection
   - get
   - list
  # BLACKLIST: patch
  # BLACKLIST: update
   - watch

- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  verbs:
  # BLACKLIST: create
  # BLACKLIST: delete
  # BLACKLIST: deletecollection
   - get
   - list
  # BLACKLIST: patch
  # BLACKLIST: update
   - watch

- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  # BLACKLIST: create
  # BLACKLIST: delete
  # BLACKLIST: deletecollection
   - get
   - list
  # BLACKLIST: patch
  # BLACKLIST: update
   - watch

- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - '*'
- apiGroups:
  - route.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - samples.operator.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - scheduling.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - security.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - servicecertsigner.config.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - storage.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - template.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - tuned.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - user.openshift.io
  resources:
  - groups
  verbs:
  # BLACKLIST: create
  # BLACKLIST: delete
  # BLACKLIST: deletecollection
   - get
   - list
  # BLACKLIST: patch
  # BLACKLIST: update
   - watch

- apiGroups:
  - user.openshift.io
  resources:
  - identities
  verbs:
  - '*'
- apiGroups:
  - user.openshift.io
  resources:
  - useridentitymappings
  verbs:
  - '*'
- apiGroups:
  - user.openshift.io
  resources:
  - users
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
