apiVersion: authorization.openshift.io/v1
kind: ClusterRole
metadata:
  name: osde2e-noalerts
rules:
- apiGroups:
  - aws.managed.openshift.io
  resources:
  - accountclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gcp.managed.openshift.io
  resources:
  - projectclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hive.openshift.io
  resources:
  - clusterdeployments
  verbs:
  - "*"
  