apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backplane-lpsre-addon-operator-olm-admin
rules:
  - apiGroups:
    - operators.coreos.com
    resources:
    - clusterserviceversions
    - installplans
    - subscriptions
    verbs:
      - get
      - list
      - watch
      - patch
      - update
      - delete
