apiVersion: v1
data:
  tls.crt: '{{hub fromSecret "openshift-acm-policies" .ManagedClusterName "tls.crt" hub}}'
  tls.key: '{{hub fromSecret "openshift-acm-policies" .ManagedClusterName "tls.key" hub}}'
kind: Secret
metadata:
  name: '{{hub (printf "%s-primary-cert-bundle-secret" .ManagedClusterName) hub}}'
  namespace: openshift-ingress
