apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: default
  namespace: openshift-ingress-operator
spec:
  defaultCertificate:
    name: '{{hub (printf "%s-primary-cert-bundle-secret" .ManagedClusterName) hub}}'
