apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dedicated-admins-openshift-codeready-workspaces
  namespace: openshift-codeready-workspaces
rules:
# BEGIN copied from openshift-logging (in dedicated-admin operator)
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  - pods/log
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - logging.openshift.io
  resources:
  - clusterloggings
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operators.coreos.com
  resources:
  - subscriptions
  - clusterserviceversions
  verbs:
  - "*"
# END copied from openshift-logging
# BEGIN Permissions for CRW
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  # DO NOT grant "get" on "secrets"!
  - list
- apiGroups:
  - org.eclipse.che
  resources:
  - '*'
  verbs:
  - '*'
# END Permissions for CRW
