apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backplane-acs-openshift-monitoring
  namespace: openshift-monitoring
rules:
# ACS SRE can view pods and logs
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  verbs:
  - get
  - list
  - watch
# ACS SRE can view statefulsets
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - get
  - list
  - watch
# ACS SRE can view services
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
# ACS SRE can use the `ocm backplane console` command
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/portforward
  verbs:
  - create