apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backplane-acs-openshift-console
  namespace: openshift-console
rules:
# ACS SRE can use the `ocm backplane console` command
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch