apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backplane-acs-rhacs-observability
  namespace: rhacs-observability
rules:
# ACS SRE can vew monitoring resources
- apiGroups:
  - monitoring.rhobs
  resources:
  - alertmanagerconfigs
  - alertmanagers
  - monitoringstacks
  - podmonitors
  - probes
  - prometheusagents
  - prometheuses
  - prometheusrules
  - scrapeconfigs
  - servicemonitors
  - thanosqueriers
  - thanosrulers
  - uiplugins
  verbs:
  - get
  - list
  - watch
# ACS SRE can view grafanas
- apiGroups:
  - grafana.integreatly.org
  resources:
  - grafanaalertrulegroups
  - grafanacontactpoints
  - grafanadashboards
  - grafanadatasources
  - grafanafolders
  - grafananotificationpolicies
  - grafanas
  verbs:
  - get
  - list
  - watch
# ACS SRE can patch persistentvolumeclaims
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - patch
# ACS SRE can restart statefulsets
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - patch