deploymentMode: "SelectorSyncSet"
selectorSyncSet:
  matchLabels:
    api.openshift.com/addon-acs-fleetshard: "true"
    api.openshift.com/addon-acs-fleetshard-qe: "true"
    api.openshift.com/addon-acs-fleetshard-dev: "true"
  matchLabelsApplyMode: "OR"
