deploymentMode: SelectorSyncSet
selectorSyncSet:
  matchExpressions:
    - key: api.openshift.com/fedramp
      operator: In
      values:
        - "true"
    - key: hive.openshift.io/version-major-minor
      operator: In
      values: ["4.12", "4.13"]
