# Lets dedicated-admins create a PersistentVolume
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:persistent-volume-provisioner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:persistent-volume-provisioner
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: dedicated-admins
