apiVersion: managed.openshift.io/v1alpha1
kind: SubjectPermission
metadata:
  name: backplane-srep-fedramp
  namespace: openshift-rbac-permissions
spec:
  permissions:
  - clusterRoleName: backplane-srep-admins-project
    namespacesAllowedRegex: "(^keycloak$|^keycloak-.*|^goalert$)"
    namespacesDeniedRegex: openshift-backplane-cluster-admin
  - clusterRoleName: dedicated-readers
    namespacesAllowedRegex: "(^keycloak$|^keycloak-.*|^goalert$)"
    namespacesDeniedRegex: openshift-backplane-cluster-admin
  subjectKind: Group
  subjectName: system:serviceaccounts:openshift-backplane-srep
