apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: hypershift-ovn-logging
spec:
  evaluationInterval:
    compliant: 2h
    noncompliant: 45s
  object-templates-raw: |
    {{- range (lookup "v1" "Namespace" "" "").items }}
    {{- if eq (index .metadata.labels "hypershift.openshift.io/hosted-control-plane") "true" }}
    - complianceType: musthave
      objectDefinition:
        kind: Namespace
        apiVersion: v1
        metadata:
          name: {{ .metadata.name }}
          annotations:
            k8s.ovn.org/acl-logging: null
    {{- end }}
    {{- end }}
  remediationAction: enforce
  severity: low
