---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
    annotations:
        policy.open-cluster-management.io/categories: CM Configuration Management
        policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
        policy.open-cluster-management.io/standards: NIST SP 800-53
    name: backplane-srep-sp
    namespace: openshift-rbac-policies
spec:
    disabled: false
    policy-templates:
        - objectDefinition:
            apiVersion: policy.open-cluster-management.io/v1
            kind: ConfigurationPolicy
            metadata:
                name: backplane-srep-sp
            spec:
                namespaceSelector:
                    exclude:
                        - openshift-backplane-cluster-admin
                    include:
                        - kube
                        - kube-*
                        - openshift
                        - openshift-*
                        - default
                        - redhat-*
                object-templates:
                    - complianceType: musthave
                      objectDefinition:
                        apiVersion: managed.openshift.io/v1alpha1
                        kind: SubjectPermission
                        metadata:
                            name: backplane-srep
                            namespace: openshift-rbac-permissions
                        spec:
                            clusterPermissions:
                                - backplane-srep-admins-cluster
                                - backplane-readers-cluster
                            permissions:
                                - allowFirst: true
                                  clusterRoleName: backplane-srep-admins-project
                                  namespacesAllowedRegex: (^kube$|^kube-.*|^openshift$|^openshift-.*|^default$|^redhat-.*)
                                  namespacesDeniedRegex: openshift-backplane-cluster-admin
                                - allowFirst: true
                                  clusterRoleName: dedicated-readers
                                  namespacesAllowedRegex: (^kube$|^kube-.*|^openshift$|^openshift-.*|^default$|^redhat-.*)
                                  namespacesDeniedRegex: openshift-backplane-cluster-admin
                            subjectKind: Group
                            subjectName: system:serviceaccounts:openshift-backplane-srep
                pruneObjectBehavior: DeleteIfCreated
                remediationAction: enforce
                severity: low
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
    name: placement-backplane-srep-sp
    namespace: openshift-rbac-policies
spec:
    clusterSelector:
        matchExpressions:
            - key: hypershift.open-cluster-management.io/hosted-cluster
              operator: In
              values:
                - "true"
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
    name: binding-backplane-srep-sp
    namespace: openshift-rbac-policies
placementRef:
    apiGroup: apps.open-cluster-management.io
    kind: PlacementRule
    name: placement-backplane-srep-sp
subjects:
    - apiGroup: policy.open-cluster-management.io
      kind: Policy
      name: backplane-srep-sp
