apiVersion: config.openshift.io/v1
applyMode: AlwaysApply
kind: ClusterVersion
name: version
patch: |-
  { "spec": { "overrides": [ { "kind": "OperatorSource", "name": "redhat-operators", "namespace": "openshift-marketplace", "unmanaged": true }, { "kind": "OperatorSource", "name": "certified-operators", "namespace": "openshift-marketplace", "unmanaged": true }, { "kind": "OperatorSource", "name": "community-operators", "namespace": "openshift-marketplace", "unmanaged": true } ] } }
patchType: merge