apiVersion: managed.openshift.io/v1alpha1
kind: SubjectPermission
metadata:
  name: backplane-cee
  namespace: openshift-rbac-permissions
spec:
  clusterPermissions:
  - backplane-cee-read-all
  subjectKind: Group
  subjectName: system:serviceaccounts:openshift-backplane-cee
