apiVersion: managed.openshift.io/v1alpha1
kind: SubjectPermission
metadata:
  name: backplane-cssre
  namespace: openshift-rbac-permissions
spec:
  clusterPermissions:
  - backplane-cssre-admins-cluster
  - backplane-cssre-readers-cluster
  permissions:
  - allowFirst: true
    clusterRoleName: backplane-cssre-admins-project
    namespacesAllowedRegex: .*
    namespacesDeniedRegex: "(^kube$|^kube-.*|^openshift$|^openshift-.*|^default$)"
  subjectKind: Group
  subjectName: system:serviceaccounts:openshift-backplane-cssre
