apiVersion: managed.openshift.io/v1alpha1
kind: SubjectPermission
metadata:
  name: backplane-cee
  namespace: openshift-rbac-permissions
spec:
  permissions:
  - allowFirst: true
    clusterRoleName: backplane-cee
    namespacesAllowedRegex: .*
  subjectKind: Group
  subjectName: system:serviceaccounts:openshift-backplane-cee
