apiVersion: managed.openshift.io/v1alpha1
kind: SubjectPermission
metadata:
  name: backplane-srep
  namespace: openshift-rbac-permissions
spec:
  clusterPermissions:
  - backplane-srep-admins-cluster
  - backplane-srep-readers-cluster
  permissions:
  - allowFirst: true
    clusterRoleName: backplane-srep-project
    namespacesAllowedRegex: "(^kube$|^kube-.*|^openshift$|^openshift-.*|^default$|^redhat-.*)"
  subjectKind: Group
  subjectName: system:serviceaccounts:openshift-backplane-srep
