---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: legacy-brand-migration
subjects:
- kind: ServiceAccount
  name: legacy-brand-migration
  namespace: openshift-console
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: legacy-brand-migration
