---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: legacy-brand-migration
rules:
- apiGroups:
  - "operator.openshift.io"
  resources:
  - consoles
  verbs:
  - get
  - list
  - patch

