apiVersion: ocmagent.managed.openshift.io/v1alpha1
kind: ManagedFleetNotification
metadata:
  name: oidc-deleted-notification
  namespace: openshift-ocm-agent-operator
spec:
  fleetNotification:
    name: oidc-deleted-notification
    summary: Cluster is in Limited Support due to unsupported cloud provider configuration
    notificationMessage: |-
      Your cluster requires action because Red Hat is either unable to access the infrastructure with the provided credentials or the credentials lack the necessary permissions to perform required actions. Please restore the credentials and permissions configured during the installation. For more details, refer to https://access.redhat.com/solutions/7098558
    resendWait: 0
    severity: Info
    limitedSupport: true
