apiVersion: batch/v1
kind: Job
metadata:
    name: osd-cluster-ready
    namespace: openshift-monitoring
spec:
    # NOTE: We're making this ridiculously high to ensure that the
    # actual code gets a chance to run to completion. However, consumers
    # should implement a sensible timeout rather than waiting forever.
    backoffLimit: 500
    template:
        metadata:
            name: osd-cluster-ready
            labels:
                # Keep this in sync with image
                managed.openshift.io/version: v0.1.53-77031d8
        spec:
            containers:
            - name: osd-cluster-ready
              # Keep the `managed.openshift.io/version` label in sync
              # with this
              image: quay.io/openshift-sre/osd-cluster-ready@sha256:ce351a409991ba6ed3c37379026b426ce5c54bdb260bae41ae051bd87d5abf51
              command: ["/root/main"]
            restartPolicy: OnFailure
            serviceAccountName: osd-cluster-ready
