---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: osd-delete-noderesolver-daemonset-bz2067978
  namespace: openshift-dns
rules:
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - get
  - list
  - delete
