---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: osd-delete-noderesolver-daemonset-bz2067978
  namespace: openshift-dns
subjects:
- kind: ServiceAccount
  name: osd-delete-noderesolver-daemonset-bz2067978
  namespace: openshift-dns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: osd-delete-noderesolver-daemonset-bz2067978
  namespace: openshift-dns
