apiVersion: batch/v1
kind: Job
metadata:
    name: osd-cluster-ready
    namespace: openshift-monitoring
spec:
    # NOTE: We're making this ridiculously high to ensure that the
    # actual code gets a chance to run to completion. However, consumers
    # should implement a sensible timeout rather than waiting forever.
    backoffLimit: 500
    template:
        metadata:
            name: osd-cluster-ready
            labels:
                # Keep this in sync with image
                managed.openshift.io/version: "v0.1.91-51f9908"
        spec:
            containers:
            - name: osd-cluster-ready
              # Keep the `managed.openshift.io/version` label in sync
              # with this
              image: "quay.io/app-sre/osd-cluster-ready@sha256:4a3dfd1efa2fe3ed563a51c58da15b788fbc14996143a1962bd1cd0afa2f5436"
              command: ["/root/main"]
            restartPolicy: OnFailure
            serviceAccountName: osd-cluster-ready
