apiVersion: monitoring.openshift.io/v1alpha1
kind: RouteMonitor
metadata:
  name: console
  namespace: openshift-route-monitor-operator
spec:
  route:
    name: console
    namespace: openshift-console
    suffix: /health
  slo:
    targetAvailabilityPercent: "99.5"
