apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backplane-mtsre-addon-operator-apis-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: backplane-mtsre-addon-operator-apis-admin
subjects:
- kind: Group
  name: system:serviceaccounts:openshift-backplane-mtsre
