deploymentMode: "SelectorSyncSet"
selectorSyncSet:
  matchExpressions:
  - key: api.openshift.com/limited-support
    operator: In
    values: ["true"]
  - key: api.openshift.com/environment
    operator: NotIn
    values: ["production"]
