apiVersion: ocmagent.managed.openshift.io/v1alpha1
kind: OcmAgent
metadata:
  name: ocmagent
  namespace: openshift-ocm-agent-operator
spec:
  agentConfig:
    ocmBaseUrl: ${OCM_BASE_URL}
    services:
    - service_logs
  replicas: 1
  tokenSecret: "ocm-access-token"
  ocmAgentConfig: "ocm-agent-config"
  ocmAgentImage: "quay.io/app-sre/ocm-agent:latest"
