apiVersion: ocmagent.managed.openshift.io/v1alpha1
kind: OcmAgent
metadata:
  name: ocmagent
  namespace: openshift-ocm-agent-operator
spec:
  ocmBaseUrl: ${OCM_BASE_URL}
  replicas: 1
  services:
  - service_logs
  tokenSecret: "ocm-access-token"
  ocmAgentConfig: "ocm-agent-config"
  ocmAgentImage: "quay.io/app-sre/ocm-agent:latest"
