apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: services-pruner
  namespace: openshift-sre-pruning
spec:
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 1
  concurrencyPolicy: Replace
  schedule: "30 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - preference:
                    matchExpressions:
                      - key: node-role.kubernetes.io/infra
                        operator: Exists
                  weight: 1
          tolerations:
            - effect: NoSchedule
              key: node-role.kubernetes.io/infra
              operator: Exists
          serviceAccountName: sre-pruner-sa
          restartPolicy: Never
          containers:
            - name: services-pruner
              image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
              imagePullPolicy: Always
              args:
                - /bin/bash
                - -c
                - >-
                  oc delete service/localmetrics-rbac-permissions-operator servicemonitor.monitoring.coreos.com/localmetrics-rbac-permissions-operator --namespace openshift-rbac-permissions --ignore-not-found
