apiVersion: config.openshift.io/v1
applyMode: ApplyOnce
kind: OAuth
name: cluster
patch: '{"spec":{"templates": {"login": {"name": "osd-oauth-templates-login"},"providerSelection":
  {"name": "osd-oauth-templates-providers"},"error": {"name": "osd-oauth-templates-errors"}}}}'
patchType: merge