apiVersion: v1
kind: ConfigMap
metadata:
  name: managed-upgrade-operator-config
  namespace: openshift-managed-upgrade-operator
data:
  config.yaml: |
    maintenance:
      controlPlaneTime: 90
      workerNodeTime: 8
    scale:
      timeOut: 30
    upgradeWindow:
      timeOut: 60
    nodeDrain:
      timeOut: 45
