apiVersion: v1
kind: ConfigMap
metadata:
  name: managed-upgrade-operator-config
  namespace: openshift-managed-upgrade-operator
data:
  config.yaml: |
    configManager:
      source: OCM
      ocmBaseUrl: ${OCM_BASE_URL}
      watchInterval: 60
    maintenance:
      controlPlaneTime: 90
      ignoredAlerts:
        controlPlaneCriticals:
        - etcdMembersDown
        - KubeDeploymentReplicasMismatch
        - ClusterOperatorDown
        - MachineWithNoRunningPhase
        - ClusterOperatorDegraded
        - CloudCredentialOperatorDown
    scale:
      timeOut: 30
    upgradeWindow:
      timeOut: 120
    nodeDrain:
      timeOut: 45
      expectedNodeDrainTime: 8
    healthCheck:
      ignoredCriticals:
      - DNSErrors05MinSRE
      - MetricsClientSendFailingSRE
      - UpgradeNodeScalingFailedSRE
      - UpgradeClusterCheckFailedSRE
    verification:
      ignoredNamespaces:
      - openshift-logging
      namespacePrefixesToCheck:
      - openshift
      - kube
      - default
