deploymentMode: "SelectorSyncSet"
selectorSyncSet:
  matchExpressions:
  - key: api.openshift.com/environment
    operator: In
    values: ["staging"]
  matchLabels:
    # Only apply on clusters owned by "Red Hat OpenShift Online" (SREP)
    api.openshift.com/legal-entity-id: "1HELaFOf2YHWwwvt3XMbT5Mja7M"
