kind: Namespace
apiVersion: v1
name: openshift-etcd
applyMode: AlwaysApply
patch: |-
  { "metadata": {"labels": {"managed.openshift.io/storage-pv-quota-exempt":"true","managed.openshift.io/service-lb-quota-exempt":"true"} } }
patchType: merge
