---
apiVersion: monitoring.openshift.io/v1alpha1
kind: ClusterUrlMonitor
metadata:
  finalizers:
  - clusterurlmonitor.routemonitoroperator.monitoring.openshift.io/finalizer
  labels:
    hive.openshift.io/managed: "true"
  name: api
spec:
  port: "6443"
  prefix: https://api.  
  slo:
    targetAvailabilityPercent: "99.0"
  suffix: /livez
