apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: increase-prometheus-storage
  namespace: openshift-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: increase-prometheus-storage
subjects:
- kind: ServiceAccount
  name: increase-prometheus-storage
  namespace: openshift-monitoring
