apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: increase-prometheus-storage
  namespace: openshift-monitoring
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - patch
  - update
