deploymentMode: "SelectorSyncSet"
selectorSyncSet:
  matchExpressions:
  - key: api.openshift.com/environment
    operator: NotIn
    values: ["production"]
  - key: hive.openshift.io/version-major-minor
    operator: NotIn
    values: ["4.0","4.1","4.2","4.3","4.4","4.5"]

