apiVersion: operators.coreos.com/v1
kind: OperatorSource
metadata:
  name: osd-curated-certified-operators
  namespace: openshift-marketplace
spec:
  authorizationToken: {}
  displayName: Certified Operators
  endpoint: https://quay.io/cnr
  publisher: Red Hat
  registryNamespace: curated-certified-operators
  type: appregistry
