deploymentMode: SelectorSyncSet
selectorSyncSet:
  matchExpressions:
  - key: hive.openshift.io/version-major-minor
    operator: In
    values: ["4.8"]
  - key: api.openshift.com/sts-acks
    operator: In
    values: ["4.9"]  
  - key: api.openshift.com/sts
    operator: In
    values: ["true"]
