deploymentMode: "SelectorSyncSet"                                                                                                                                                                          
selectorSyncSet:
  resourceApplyMode: Upsert
  matchExpressions:
  - key: api.openshift.com/environment
    operator: In
    values: ["staging", "integration"]
