---
apiVersion: monitoring.openshift.io/v1alpha1
kind: ClusterUrlMonitor
metadata:
  name: api
spec:
  port: "6443"
  prefix: https://api.
  slo:
    targetAvailabilityPercent: "99.0"
  suffix: /livez
  domainRef: hcp
