---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ocpbugs-15043-read-pullsecret
  namespace: openshift-config
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ocpbugs-15043-delete-machines
  namespace: openshift-machine-api
rules:
- apiGroups:
  - "machine.openshift.io"
  resources:
  - machines
  verbs:
  - get
  - list
  - delete
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ocpbugs-15043-read-configmap
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ocpbugs-15043-manage-lastrun-cm
  namespace: openshift-config
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - create
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ocpbugs-15043-inspect-pods
rules:
- apiGroups:
  - 
  resources:
  - pods
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ocpbugs-15043-read-clusterversion
rules:
- apiGroups:
    - "config.openshift.io"
  resources:
    - clusterversions
  verbs:
    - get
    - list
- apiGroups:
    - ""
  resources:
    - nodes
  verbs:
    - get
    - list
    - watch
