---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ocpbugs-15043-read-pullsecret
  namespace: openshift-config
subjects:
- kind: ServiceAccount
  name: ocpbugs-15043
  namespace: openshift-config
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ocpbugs-15043-read-pullsecret
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ocpbugs-15043-delete-machines
  namespace: openshift-machine-api
subjects:
- kind: ServiceAccount
  name: ocpbugs-15043
  namespace: openshift-config
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ocpbugs-15043-delete-machines
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ocpbugs-15043-read-muo-configmap
  namespace: openshift-managed-upgrade-operator
subjects:
- kind: ServiceAccount
  name: ocpbugs-15043
  namespace: openshift-config
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ocpbugs-15043-read-configmap
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ocpbugs-15043-read-oao-configmap
  namespace: openshift-ocm-agent-operator
subjects:
- kind: ServiceAccount
  name: ocpbugs-15043
  namespace: openshift-config
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ocpbugs-15043-read-configmap
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ocpbugs-15043-manage-lastrun-cm
  namespace: openshift-config
subjects:
- kind: ServiceAccount
  name: ocpbugs-15043
  namespace: openshift-config
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ocpbugs-15043-manage-lastrun-cm
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ocpbugs-15043-inspect-pods
  namespace: openshift-sre-pruning
subjects:
- kind: ServiceAccount
  name: ocpbugs-15043
  namespace: openshift-config
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ocpbugs-15043-inspect-pods
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ocpbugs-15043-inspect-pods
  namespace: openshift-monitoring
subjects:
- kind: ServiceAccount
  name: ocpbugs-15043
  namespace: openshift-config
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ocpbugs-15043-inspect-pods
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ocpbugs-15043-read-clusterversion
subjects:
- kind: ServiceAccount
  name: ocpbugs-15043
  namespace: openshift-config
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ocpbugs-15043-read-clusterversion
