apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bz2008282-pruning-rolebinding
  namespace: openshift
roleRef:
  kind: Role
  name: bz2008282-pruning-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: bz2008282-pruning-sa
  namespace: openshift
