---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloud-ingress-operator
  namespace: openshift-cloud-ingress-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: custom-domains-operator
  namespace: openshift-custom-domains-operator
