deploymentMode: "SelectorSyncSet"
selectorSyncSet:
    matchLabels:
      hive.openshift.io/cluster-platform: aws
    matchExpressions:
    - key: api.openshift.com/fedramp
      operator: NotIn
      values:
      - "true"
    - key: ext-managed.openshift.io/legacy-ingress-support
      operator: NotIn
      values: ["false"]
    resourceApplyMode: Upsert
