apiVersion: operator.openshift.io/v1
applyMode: Sync
kind: DNS
name: default
patchtype: merge
patch: '{"spec": {"nodePlacement": {"tolerations": [{"effect": "NoSchedule", "key": "node-role.kubernetes.io/infra", "operator": "Exists"}, {"effect": "NoSchedule", "key": "node-role.kubernetes.io/master", "operator": "Exists"}]}}}'
