---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: capa-annotator
rules:
- apiGroups:
  - work.open-cluster-management.io
  resources:
  - manifestworks                 
  verbs:
  - get
  - patch
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - managedcluster
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list