kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: capa-annotator
subjects:
- kind: ServiceAccount
  name: capa-annotator
  namespace: openshift-capa-annotator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: capa-annotator