apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
metadata:
  name: custom-kubelet
spec:
  machineConfigSelector:
    matchLabels:
      managed.openshift.io/custom-kubelet: true
  kubeletConfig:
    EnforceNodeAllocatable:
      system-reserved:
        - "cpu=1000m,memory=1Gi"

