deploymentMode: "SelectorSyncSet"
selectorSyncSet:
  resourceApplyMode: Upsert
  matchExpressions:
  - key: api.openshift.com/wif
    operator: In
    values: ["true"]
  - key: api.openshift.com/fedramp
    operator: NotIn
    values:
      - "true"
