---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: pki-operator-annotator-4-16
  namespace: openshift-pki-operator-annotator
  annotations:
    kubernetes.io/description: "Patches 4.16 ManifestWork to fixed pki-operator version https://issues.redhat.com/browse/OSD-27987"
spec:
  schedule: "*/5 * * * *" # Every five minutes
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        metadata:
          name: pki-operator-annotator
          namespace: openshift-pki-operator-annotator
          annotations:
            kubernetes.io/description: "Patches 4.16 ManifestWork to fixed pki-operator version https://issues.redhat.com/browse/OSD-27987"
        spec:
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - preference:
                    matchExpressions:
                      - key: node-role.kubernetes.io/infra
                        operator: Exists
                  weight: 1
          tolerations:
            - effect: NoSchedule
              key: node-role.kubernetes.io/infra
              operator: Exists
          containers:
            - name: pki-operator-annotator
              image: image-registry.openshift-image-registry.svc:5000/openshift/tools:latest
              imagePullPolicy: Always
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                runAsNonRoot: true
              env:
                # oc adm release info --image-for hypershift quay.io/openshift-release-dev/ocp-release:4.16.34-multi
                - name: IMAGE
                  value: "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:9c417743007bbefa3909e95284113b1e9a43be9124464f6bbb62676009546da5"
                # What Y stream this annotator is looking to patch
                - name: MAJOR_MINOR_VER
                  value: "4.16"
                # What Z stream includes the fix, meaning we don't patch at X.Y.Z and later (eg 4.16.34 has the fix)
                - name: Z_STREAM_FIXED_VER
                  value: "34"
              volumeMounts:
                - name: scripts
                  mountPath: /tmp/scripts
              command:
                - /bin/bash
              args:
                - /tmp/scripts/patch.sh
          volumes:
            - name: scripts
              configMap:
                name: pki-operator-annotator
          serviceAccountName: pki-operator-annotator
          automountServiceAccountToken: true
          restartPolicy: Never
