apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: 5min-full-backup
  namespace: openshift-velero
spec:
  schedule: '*/5 * * * *'
  template:
    includedNamespaces:
    - '*'
    ttl: 0h25m0s
