deploymentMode: "SelectorSyncSet"
selectorSyncSet:
  resourceApplyMode: Sync
  matchExpressions:
    - key: api.openshift.com/legal-entity-id
      operator: In
      values: "${{ALLOW_CORDON_WORKER_NODE_ENTITY_IDS}}"
    - key: api.openshift.com/fedramp
      operator: NotIn
      values:
        - "true"
