deploymentMode: "SelectorSyncSet"
selectorSyncSet:
  resourceApplyMode: Sync
  matchExpressions:
  # This will be removed once OSD-14568 has been completed
  - key: hive.openshift.io/version-major-minor
    operator: In
    values: 
      - "4.12"
      - "4.13"
      # Customers can continue to opt-in to keep using CIO in 4.14+, so disable CPMS on those clusters
      # until the completion of OSD-14568
      - "4.14"
  - key: ext-hypershift.openshift.io/cluster-type
    operator: NotIn
    values: ["management-cluster"]
