deploymentMode: "SelectorSyncSet"
selectorSyncSet:
  matchLabels:
    api.openshift.com/addon-advanced-cluster-management: "true"
  matchExpressions:
  - key: api.openshift.com/environment
    operator: In
    values: ["staging", "integration"]
