---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "sre-remove-dns-tolerations"
rules:
- apiGroups:
  - "operator.openshift.io"
  resources:
  - "dnses"
  verbs:
  - get
  - patch
