---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "sre-remove-dns-tolerations"
roleRef:
  kind: ClusterRole
  name: "sre-remove-dns-tolerations"
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: "sre-remove-dns-tolerations"
  namespace: "openshift-sre-pruning"
