apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: suricata
  namespace: openshift-suricata
spec:
  selector:
    matchLabels:
      name: suricata
  template:
    metadata:
      labels:
        name: suricata
    spec:
      containers:
      - env:
        - name: OO_PAUSE_ON_START
          value: "false"
        image: quay.io/app-sre/suricata@sha256:dd08ab702198479f1e0b76df7d7f282fbad4e0254930862758e55fdc575de1c1
        imagePullPolicy: IfNotPresent
        name: suricata
        resources:
          limits:
            cpu: 900m
            memory: 900Mi
          requests:
            cpu: 100m
            memory: 50Mi
        securityContext:
          capabilities:
            add: ["NET_ADMIN", "NET_RAW"]
        volumeMounts:
        - mountPath: /host/var/log
          name: host-filesystem
      - name: log-cleaner
        image: quay.io/app-sre/log-cleaner@sha256:40f10248c444d60316a29dac29075a18eeadf5a8556a8824185b5955656005e9
        volumeMounts:
        - mountPath: /host/var/log
          name: host-filesystem
      dnsPolicy: ClusterFirst
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: suricata-sa
      tolerations:
      - operator: Exists
      volumes:
      - hostPath:
          path: /var/log
        name: host-filesystem
