apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: suricata
  namespace: openshift-suricata
spec:
  selector:
    matchLabels:
      name: suricata
  template:
    metadata:
      labels:
        name: suricata
    spec:
      containers:
      - env:
        - name: OO_PAUSE_ON_START
          value: "false"
        image: quay.io/app-sre/suricata@sha256:4b7b4ff88311cd2a55699d8fda8491fdf46cb70c9edded29fff0c8dd6889849e
        imagePullPolicy: IfNotPresent
        name: suricata
        resources:
          limits:
            cpu: 900m
            memory: 900Mi
          requests:
            cpu: 100m
            memory: 50Mi
        securityContext:
          capabilities:
            add: ["NET_ADMIN", "NET_RAW"]
        volumeMounts:
        - mountPath: /host/var/log
          name: host-filesystem
      - name: log-cleaner
        image: quay.io/app-sre/log-cleaner@sha256:3ded368be76bf83c64ab2d239ccff5a8aff60ccf89f2758d93cdebc22b58a015
        volumeMounts:
        - mountPath: /host/var/log
          name: host-filesystem
      dnsPolicy: ClusterFirst
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: suricata-sa
      tolerations:
      - operator: Exists
      volumes:
      - hostPath:
          path: /var/log
        name: host-filesystem
