apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: suricata
  namespace: openshift-suricata
spec:
  selector:
    matchLabels:
      name: suricata
  template:
    metadata:
      labels:
        name: suricata
    spec:
      containers:
      - env:
        - name: OO_PAUSE_ON_START
          value: "false"
        image: quay.io/app-sre/suricata@sha256:69f79f15ed54d710fcfa24fe4031112f82f5c4dc68abba5d1f5a0cc0fa568d0c
        imagePullPolicy: IfNotPresent
        name: suricata
        resources:
          limits:
            cpu: 900m
            memory: 900Mi
          requests:
            cpu: 100m
            memory: 50Mi
        securityContext:
          capabilities:
            add: ["NET_ADMIN", "NET_RAW"]
        volumeMounts:
        - mountPath: /host/var/log
          name: host-filesystem
      - name: log-cleaner
        image: quay.io/app-sre/log-cleaner@sha256:78ea446c88abb07e474f939f72ab73616f5915f166355f8810aee4c1468a3278
        volumeMounts:
        - mountPath: /host/var/log
          name: host-filesystem
      dnsPolicy: ClusterFirst
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: suricata-sa
      tolerations:
      - operator: Exists
      volumes:
      - hostPath:
          path: /var/log
        name: host-filesystem
