apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: suricata
  namespace: openshift-suricata
spec:
  selector:
    matchLabels:
      name: suricata
  template:
    metadata:
      labels:
        name: suricata
    spec:
      containers:
      - env:
        - name: OO_PAUSE_ON_START
          value: "false"
        image: quay.io/app-sre/suricata@sha256:577fc9bc4816cf9298d12911d000b953dd4e7df4cf6502d4aa5e78219ba0357b
        imagePullPolicy: IfNotPresent
        name: suricata
        resources:
          limits:
            cpu: 900m
            memory: 900Mi
          requests:
            cpu: 100m
            memory: 50Mi
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
        - mountPath: /host/
          name: host-filesystem
      dnsPolicy: ClusterFirst
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: suricata-sa
      volumes:
      - hostPath:
          path: /
        name: host-filesystem
