apiVersion: managed.openshift.io/v1alpha1
kind: SubjectPermission
metadata:
  name: backplane-mcs-tier-two-service-cluster
  namespace: openshift-rbac-permissions
spec:
  clusterPermissions:
  - backplane-mcs-tier-two-service-cluster-cluster
  - view
  permissions:
  - clusterRoleName: dedicated-readers
    namespacesAllowedRegex: "(^hypershift.*|^uhc.*|^ocm.*|^klusterlet.*|^open-cluster-management.*)"
    namespacesDeniedRegex: openshift-backplane-cluster-admin
  subjectKind: Group
  subjectName: system:serviceaccounts:openshift-backplane-mcs-tier-two
