deploymentMode: SelectorSyncSet
selectorSyncSet:
  resourceApplyMode: "Sync"
  matchExpressions:
    - key: api.openshift.com/fedramp
      # Insights operator does not exist in FedRAMP
      # https://issues.redhat.com/browse/OSD-13685
      operator: NotIn
      values:
        - "true"
