apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backplane-cee-pcap-collector
  namespace: openshift-backplane-managed-scripts
rules:
- apiGroups:
  - ""
  resourceNames:
  - pcap-collector-creds
  resources:
  - secrets
  verbs:
  - delete
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
### END
