apiVersion: operator.openshift.io/v1
kind: KubeAPIServer
name: cluster
applyMode: AlwaysApply
# for non-prod we had already deployed the override.  undo this as we now prefer flowschema patch.
patch: '[{ "op": "remove", "path": "/spec/unsupportedConfigOverrides" }]'
patchType: json
