apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: sre-managed-node-metadata-operator-alerts
    role: alert-rules
  name: sre-managed-node-metadata-operator-alerts
  namespace: openshift-monitoring
spec:
  groups:
  - name: sre-managed-node-metadata-operator-alerts
    rules:
    - alert: MNMOTooManyReconcileErrors15MinSRE
      # If the amount of reconciliation errors in the last 15 minutes is > 5 trigger an alert.
      # Currently the window is 90 minutes, because the reconcile loop uses some backoff mechanism for retries and with a 90 minute window the alert will keep on firing.
      expr: increase(controller_runtime_reconcile_total{controller="machineset_controller", service="openshift-managed-node-metadata-operator-metrics-service", result="error"}[90m]) >= 5
      for: 15m
      labels:
        severity: warning
        namespace: "{{ $labels.namespace }}"
        maturity: "immature"
        source: "https://issues.redhat.com//browse/OSD-9911"
      annotations:
        message: At least 5 reconciliations of the MNMO operator ( {{ $labels.name }} ) have failed in the past 15 minutes.
        link: "https://github.com/openshift/ops-sop/blob/master/v4/alerts/MNMOTooManyReconcileFailures.md"
