apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: sre-dns-alerts
    role: alert-rules
  name: sre-dns-alerts
  namespace: openshift-monitoring
spec:
  groups:
  - name: sre-dns-alerts
    rules:
    - alert: DNSLatencyOver200ms5MinSRE
      expr: max_over_time(dns_latency_milliseconds_sum[5m]) > 0.2
      labels:
        severity: critical
        namespace: openshift-monitoring
    - alert: DNSErrors05MinSRE
      expr: rate(dns_failure_failure_total[5m]) > 0
      for: 5m
      labels:
        severity: critical
        namespace: openshift-monitoring
      annotations:
        message: DNS checks have been failing for the past 5 minutes on pod- {{ $labels.pod }}
