apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus:
    role: recording-rules
  name: sre-build-test-job
  namespace: openshift-monitoring
spec:
  groups:
  - name: sre-build-test-job
    rules:
    - record: sre-kube-build-test-job-success-rate
      expr: sum(kube_job_complete{namespace="openshift-build-test"}) + sum(kube_job_failed{namespace="openshift-build-test"}) / sum(kube_job_status_succeeded{namespace="openshift-build-test"})
