deploymentMode: "SelectorSyncSet"
selectorSyncSet:
  matchLabels:
      api.openshift.com/addon-managed-api-service: "true"
  matchExpressions:
  - key: api.openshift.com/environment
    operator: NotIn
    values: ["production"]
