apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: layered-cs-sre-admin-cluster
rules:
# CS SRE can manage projects
- apiGroups:
  - config.openshift.io
  resources:
  - projects
  verbs:
  - '*'
- apiGroups:
  - project.openshift.io
  resources:
  - projects
  verbs:
  - '*'
# CS SRE can manage namespaces
- apiGroups:
  - ""
  resources:
  - namespaces
  - namespaces/finalize
  verbs:
  - '*'
# CS SRE can update existing groups (enables break glass)
- apiGroups:
  - user.openshift.io
  resources:
  - groups
  verbs:
  - patch
  - update
# CS SRE can interact with RHMI ClusterResourceQuotas (Only for LA)
- apiGroups:
  - quota.openshift.io
  resources:
  - clusterresourcequotas/status
  - clusterresourcequotas
  verbs:
  - '*'
  resourceNames:
  - rhmi-loadbalancer-quota
  - rhmi-persistent-volume-quota