apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backplane-mcs-tier-two
  namespace: openshift-monitoring
rules:
# MCS Tier Two Support Engineers can portforward monitoring pods
- apiGroups:
  - ""
  resources:
  - pods/portforward
  verbs:
  - create
