apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backplane-mcs-tier-two-mustgather
  namespace: openshift-must-gather-operator
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:openshift-backplane-mcs-tier-two
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: backplane-mcs-tier-two-mustgather
