---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "sre-replace-packageserver-csv"
  namespace: "openshift-operator-lifecycle-manager"
rules:
- apiGroups:
  - "operators.coreos.com"
  resources:
  - "clusterserviceversions"
  verbs:
  - list
  - get
  - watch
  - delete
