---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "sre-replace-packageserver-csv"
  namespace: "openshift-operator-lifecycle-manager"
roleRef:
  kind: Role
  name: "sre-replace-packageserver-csv"
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: "sre-replace-packageserver-csv"
  namespace: "openshift-operator-lifecycle-manager"
