deploymentMode: "SelectorSyncSet"
selectorSyncSet:
  resourceApplyMode: "Sync"
  matchLabels:
    api.openshift.com/managed: "true"
  matchExpressions:
  - key: api.openshift.com/fedramp
    operator: NotIn
    values: ["true"]
  - key: hive.openshift.io/version-major-minor
    operator: In
    values: ["4.12", "4.13", "4.14", "4.15"]
