---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: osde2e-noalerts
  # pipelines will force NS to this, so just going to set here so it's not confusing to debug.
  namespace: cluster-scope
spec:
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 3
  concurrencyPolicy: Replace
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: osde2e-noalerts
          restartPolicy: Never
          containers:
          - name: osde2e-noalerts
            image: quay.io/openshift/origin-cli:4.4
            imagePullPolicy: Always
            args:
            - /bin/bash
            - -c
            - |
              # Org IDs to apply to are for osde2e: 1aV37K1VQv2zSStwSkdwBNOUBGI, 1MSRrYaelBWudhmVktupE2t7ABy
              # https://github.com/openshift/ops-sop/blob/master/v4/howto/noalerts.md#hive-production
              
              NAMESPACES=()

              # AWS osde2e namespaces:
              NAMESPACES+=($(oc get accountclaim --all-namespaces -o jsonpath='{.items[?(@.spec.legalEntity.id=="1aV37K1VQv2zSStwSkdwBNOUBGI")].metadata.namespace}'))
              NAMESPACES+=($(oc get projectclaim --all-namespaces -o jsonpath='{.items[?(@.spec.legalEntity.id=="1aV37K1VQv2zSStwSkdwBNOUBGI")].metadata.namespace}'))
              
              # GCP osde2e namespaces:
              NAMESPACES+=($(oc get projectclaim --all-namespaces -o jsonpath='{.items[?(@.spec.legalEntity.id=="1MSRrYaelBWudhmVktupE2t7ABy")].metadata.namespace}'))
              NAMESPACES+=($(oc get accountclaim --all-namespaces -o jsonpath='{.items[?(@.spec.legalEntity.id=="1MSRrYaelBWudhmVktupE2t7ABy")].metadata.namespace}'))
              
              # Label each unlabeled CD in each NS:
              for NS in ${NAMESPACES[@]};
              do
                  for CD in $(oc -n $NS get cd -o jsonpath="{range .items[*]}{.metadata.name},{.metadata.labels},{'\n'} {end}" | grep -v "ext-managed.openshift.io/noalerts:true" | awk -F, '{print $1}')
                  do
                      echo "Adding 'ext-managed.openshift.io/noalerts' label to ClusterDeployment '$CD' in Namespace '$NS'"
                      oc -n $NS label clusterdeployment $CD ext-managed.openshift.io/noalerts="true" --overwrite=true
                      echo "Adding legacy 'api.openshift.com/noalerts' label to ClusterDeployment '$CD' in Namespace '$NS'"
                      oc -n $NS label clusterdeployment $CD api.openshift.com/noalerts="true" --overwrite=true
                  done
              done
