apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sre-pruner-sre-users
rules:
  # deployment pruning
  - apiGroups:
      - "user.openshift.io"
    resources:
      - users
    verbs:
      - list
      - get
      - delete
