apiVersion: managed.openshift.io/v1alpha1
kind: SubjectPermission
metadata:
  name: backplane-srep-hive
  namespace: openshift-rbac-permissions
spec:
  permissions:
  - allowFirst: true
    clusterRoleName: backplane-srep-hive-project
    namespacesAllowedRegex: "(^uhc-.*)"
  - allowFirst: true
    clusterRoleName: dedicated-readers
    namespacesAllowedRegex: "(^hive$|^backplane$|^uhc-.*|^.*-operator$)"
  subjectKind: Group
  subjectName: system:serviceaccounts:openshift-backplane-srep
