apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: sre-slo-recording-rules
    role: recording-rules
  name: sre-slo-recording-rules
  namespace: openshift-monitoring
spec:
  groups:
    - name: sre-slo.rules
      rules:
        - expr: sre:telemetry:managed_labels * on (sre) group_left(probe_url) label_replace(probe_success{probe_url=~".+api.+"}, "sre", "true", "", "")
          record: sre:slo:probe_success_api
        - expr: sre:telemetry:managed_labels * on (sre) group_left(probe_url) label_replace(probe_success{probe_url=~".+console.+"}, "sre", "true", "", "")
          record: sre:slo:probe_success_console
        - expr: label_replace(sum by (code, method) (imageregistry_http_requests_total), "sre", "true", "", "") * on (sre) group_left(_id,provider,region,version) sre:telemetry:managed_labels
          record: sre:slo:imageregistry_http_requests_total
        - expr: label_replace(sum by (code, verb, subresource) (oauth_server_requests_total), "sre", "true", "", "") * on (sre) group_left(_id,provider,region,version) sre:telemetry:managed_labels
          record: sre:slo:oauth_server_requests_total
        - expr: sre:telemetry:managed_labels * on (sre) group_left(probe_url) label_replace(sum_over_time(((count((sum(rate(apiserver_request_total{job="apiserver", code=~"(400|5..)"}[5m]))/sum(rate(apiserver_request_total{job="apiserver"}[5m]))) == 1)*(count((sum(rate(apiserver_request_total{job="apiserver", code=~"(400|5..)"}[5m]))/sum(rate(apiserver_request_total{job="apiserver"}[5m]))) == 1)/2+4.5*(1-(count(sum(rate(apiserver_request_total{job="apiserver", code=~"(400|5..)"}[5m] offset 30s))/sum(rate(apiserver_request_total{job="apiserver"}[5m] offset 30s)) == 1) or vector(0))))) or vector(0))[4w:30s]), "sre", "true", "", "")
          record: sre:sla:outage_minutes_28d
