apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: sre-internal-recording-rules
    role: recording-rules
  name: sre-internal-recording-rules
  namespace: openshift-monitoring
spec:
  groups:
    - name: sre-internal-record.rules
      rules:
        - expr: sre:telemetry:managed_labels * on(version) group_right (_id, provider, region) label_replace((avg without (endpoint, instance, job, namespace, pod, prometheus, service) (upgradeoperator_healthcheck_failed)), "SRE", "true", "", "")
          record: sre:record:upgradeoperator_upgrade_healthcheck_result