apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: sre-internal-slo-recording-rules
    role: recording-rules
  name: sre-internal-slo-recording-rules
  namespace: openshift-monitoring
spec:
  groups:
    - name: sre-internal-slo.rules
      rules:
        - expr: sre:telemetry:managed_labels * on (sre) group_left(version, alerts, upgradeconfig_name) label_replace(topk(1, upgradeoperator_upgrade_result), "sre", "true", "", "")
          record: sre:slo:upgradeoperator_upgrade_result
