---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: osd-rebalance-infra-nodes-openshift-pod-rebalance
  namespace: openshift-image-registry
subjects:
- kind: ServiceAccount
  name: osd-rebalance-infra-nodes
  namespace: openshift-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: osd-rebalance-infra-nodes-openshift-pod-rebalance
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: osd-rebalance-infra-nodes-openshift-pod-rebalance
  namespace: openshift-custom-domains-operator
subjects:
- kind: ServiceAccount
  name: osd-rebalance-infra-nodes
  namespace: openshift-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: osd-rebalance-infra-nodes-openshift-pod-rebalance
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: osd-rebalance-infra-nodes-openshift-pod-rebalance
  namespace: openshift-managed-node-metadata-operator
subjects:
- kind: ServiceAccount
  name: osd-rebalance-infra-nodes
  namespace: openshift-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: osd-rebalance-infra-nodes-openshift-pod-rebalance
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: osd-rebalance-infra-nodes-openshift-pod-rebalance
  namespace: openshift-monitoring
subjects:
- kind: ServiceAccount
  name: osd-rebalance-infra-nodes
  namespace: openshift-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: osd-rebalance-infra-nodes-openshift-pod-rebalance
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: osd-rebalance-infra-nodes-openshift-pod-rebalance
  namespace: openshift-must-gather-operator
subjects:
- kind: ServiceAccount
  name: osd-rebalance-infra-nodes
  namespace: openshift-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: osd-rebalance-infra-nodes-openshift-pod-rebalance
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: osd-rebalance-infra-nodes-openshift-pod-rebalance
  namespace: openshift-network-operator
subjects:
- kind: ServiceAccount
  name: osd-rebalance-infra-nodes
  namespace: openshift-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: osd-rebalance-infra-nodes-openshift-pod-rebalance
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: osd-rebalance-infra-nodes-openshift-pod-rebalance
  namespace: openshift-ocm-agent-operator
subjects:
- kind: ServiceAccount
  name: osd-rebalance-infra-nodes
  namespace: openshift-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: osd-rebalance-infra-nodes-openshift-pod-rebalance
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: osd-rebalance-infra-nodes-openshift-pod-rebalance
  namespace: openshift-osd-metrics
subjects:
- kind: ServiceAccount
  name: osd-rebalance-infra-nodes
  namespace: openshift-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: osd-rebalance-infra-nodes-openshift-pod-rebalance
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: osd-rebalance-infra-nodes-openshift-pod-rebalance
  namespace: openshift-rbac-permissions
subjects:
- kind: ServiceAccount
  name: osd-rebalance-infra-nodes
  namespace: openshift-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: osd-rebalance-infra-nodes-openshift-pod-rebalance
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: osd-rebalance-infra-nodes-openshift-pod-rebalance
  namespace: openshift-route-monitor-operator
subjects:
- kind: ServiceAccount
  name: osd-rebalance-infra-nodes
  namespace: openshift-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: osd-rebalance-infra-nodes-openshift-pod-rebalance
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: osd-rebalance-infra-nodes-openshift-pod-rebalance
  namespace: openshift-splunk-forwarder-operator
subjects:
- kind: ServiceAccount
  name: osd-rebalance-infra-nodes
  namespace: openshift-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: osd-rebalance-infra-nodes-openshift-pod-rebalance
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: osd-rebalance-infra-nodes-openshift-pod-rebalance
  namespace: openshift-velero
subjects:
- kind: ServiceAccount
  name: osd-rebalance-infra-nodes
  namespace: openshift-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: osd-rebalance-infra-nodes-openshift-pod-rebalance
