apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backplane-cse-readers-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: backplane-cse-readers-cluster
subjects:
- kind: Group
  name: system:serviceaccounts:openshift-backplane-cse
