apiVersion: operators.coreos.com/v1
kind: CatalogSourceConfig
metadata:
  name: installed-redhat-openshift-operators
  namespace: openshift-marketplace
spec:
  csDisplayName: Red Hat Operators
  csPublisher: Red Hat
  packages: elasticsearch-operator
  targetNamespace: openshift-operators
