apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    csc-owner-name: installed-redhat-openshift-operators
    csc-owner-namespace: openshift-marketplace
  name: elasticsearch-operator
  namespace: openshift-operators
spec:
  channel: preview
  installPlanApproval: Automatic
  name: elasticsearch-operator
  source: installed-redhat-openshift-operators
  sourceNamespace: openshift-operators
  startingCSV: elasticsearch-operator.4.1.4-201906271212
