apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    csc-owner-name: installed-redhat-openshift-logging
    csc-owner-namespace: openshift-marketplace
  name: cluster-logging
  namespace: openshift-logging
spec:
  channel: preview
  installPlanApproval: Automatic
  name: cluster-logging
  source: installed-redhat-openshift-logging
  sourceNamespace: openshift-logging
  startingCSV: clusterlogging.4.1.4-201906271212
