apiVersion: monitoring.rhobs/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: sre-dynatrace-workloads
    role: alert-rules
  name: sre-dynatrace-workloads
  namespace: openshift-observability-dynatrace
spec:
  groups:
  - name: sre-dynatrace-workloads-failing
    rules:
    - alert: DynatraceMonitoringStackDownSRE
      expr: |
          sum(hypershift_hostedclusters) > 0 and (
          kube_deployment_status_replicas{deployment="dynatrace-operator", namespace="dynatrace"} == 0 or
          kube_deployment_status_replicas{deployment="dynatrace-webhook", namespace="dynatrace"} == 0 or
          kube_deployment_status_replicas{deployment="opentelemetry-dynatrace-collector", namespace="dynatrace"} == 0 or
          kube_statefulset_status_replicas{statefulset=~".*-activegate", namespace="dynatrace"} == 0 or
          kube_daemonset_status_desired_number_scheduled{daemonset=~".*-oneagent", namespace="dynatrace"} == 0 )
      for: 15m
      labels:
        namespace: dynatrace
        severity: warning
      annotations:
        summary: "Dynatrace Workloads are failing on the Management Cluster"
        description: "The Dynatrace deployment on the Management Cluster has failed to be deployed for 15 mins"

  - name: sre-dynatrace-monitoring-stack-degraded
    rules:
    - alert: DynatraceOperatorDegradedSRE
      expr: (sum(kube_deployment_spec_replicas{deployment="dynatrace-operator", namespace="dynatrace"}) without (deployment, instance, pod)) - (sum(kube_deployment_status_replicas_available{deployment="dynatrace-operator", namespace="dynatrace"}) without (deployment, instance, pod)) > 0
      for: 10m
      labels:
        namespace: dynatrace
        severity: warning
      annotations:
        summary: "The Dynatrace Operator is Degraded"
        description: "{{$value}} pods are not running out of total pods for the Dynatrace Operator"
  
    - alert: DynatraceWebhookDegradedSRE
      expr: (sum(kube_deployment_spec_replicas{deployment="dynatrace-webhook", namespace="dynatrace"}) without (deployment, instance, pod)) - (sum(kube_deployment_status_replicas_available{deployment="dynatrace-webhook", namespace="dynatrace"}) without (deployment, instance, pod)) > 0
      for: 10m
      labels:
        namespace: dynatrace
        severity: warning
      annotations:
        summary: "Dynatrace Webhook is Degraded"
        description: "{{$value}} pods are not running out of total pods for the Dynatrace Webhook"

    - alert: DynatraceOpenTelemetryCollectorDegradedSRE
      expr: (sum(kube_deployment_spec_replicas{deployment="opentelemetry-dynatrace-collector", namespace="dynatrace"}) without (deployment, instance, pod)) - (sum(kube_deployment_status_replicas_available{deployment="opentelemetry-dynatrace-collector", namespace="dynatrace"}) without (deployment, instance, pod)) == 0
      for: 15m
      labels:
        namespace: dynatrace
        severity: warning
      annotations:
        summary: "Dynatrace OTEL Collector is Degraded"
        description: "{{$value}} pods are not running out of total pods for the OpenTelemetry Dynatrace Collector"

    - alert: DynatraceActiveGateDegradedSRE
      expr: (sum(kube_statefulset_status_replicas{statefulset=~".*-activegate", namespace="dynatrace"}) without (deployment, instance, pod)) - (sum(kube_statefulset_status_replicas_ready{statefulset=~".*-activegate", namespace="dynatrace"}) without (deployment, instance, pod)) > 0
      for: 15m
      labels:
        namespace: dynatrace
        severity: warning
      annotations:
        summary: "Dynatrace ActiveGate is Degraded"
        description: "{{$value}} pods are not running out of total pods for Dynatrace ActiveGate"

    - alert: DynatraceOneAgentDegradedSRE
      expr: sum(kube_daemonset_status_desired_number_scheduled{daemonset=~".*-oneagent", namespace="dynatrace"}) without (daemonset, instance, pod) - sum(kube_daemonset_status_number_ready{daemonset=~".*-oneagent", namespace="dynatrace"}) without (daemonset, instance, pod) > 0
      for: 15m
      labels:
        namespace: dynatrace
        severity: warning
      annotations:
        summary: "Dynatrace OneAgent is Degraded"
        description: "{{$value}} pods are not running out of total pods for Dynatrace OneAgent"  

    - alert: DynatracePodRestartsStuckSRE
      expr: kube_pod_container_status_restarts_total{namespace="dynatrace"} > 0 and increase(kube_pod_container_status_restarts_total{namespace="dynatrace"}[15m]) > 0
      for: 15m
      labels:
        namespace: dynatrace
        severity: warning
      annotations:
        summary: "Pod Restarts Stuck Alert"
        description: "At least one pod in the 'dynatrace' namespace has been stuck in restarts for the last 15 minutes."

