apiVersion: authorization.openshift.io/v1
kind: ClusterRoleBinding
metadata:
  name: osde2e-noalerts
roleRef:
  name: osde2e-noalerts
subjects:
- kind: ServiceAccount
  name: osde2e-noalerts
  # pipelines will force NS to this, so just going to set here so it's not confusing to debug.
  namespace: cluster-scope
