apiVersion: operator.openshift.io/v1
applyMode: ApplyOnce
kind: IngressController
name: default
namespace: openshift-ingress-operator
# patch registry to deploy on infras: https://docs.openshift.com/container-platform/4.2/machine_management/creating-infrastructure-machinesets.html#infrastructure-moving-registry_creating-infrastructure-machinesets
patch: '[{"op":"remove","path":"/spec/nodePlacement"}]'
patchType: json
