apiVersion: managed.openshift.io/v1alpha1
kind: SubjectPermission
metadata:
  name: backplane-mkrts-admins
  namespace: openshift-rbac-permissions
spec:
  permissions:
  - allowFirst: true
    clusterRoleName: admin
    namespacesAllowedRegex: (^redhat-managed-kafka-.*|^redhat-kas-fleetshard-.*)
  subjectKind: Group
  subjectName: system:serviceaccounts:openshift-backplane-rts
