apiVersion: machine.openshift.io/v1beta1
kind: MachineHealthCheck
metadata:
  name: srep-management-cluster-node-recovery
  namespace: openshift-machine-api
spec:
  selector:
    matchExpressions:
    # Until we have a way to propagate labels from machinepools to machines, e.g. https://issues.redhat.com/browse/HIVE-2320
    # we need to select machines based on machinepool name
    - key: machine.openshift.io/cluster-api-machine-role
      operator: In
      values:
      - "serving-1"
      - "serving-2"
      - "serving-3"
      - "serving-4"
      - "serving-5"
      - "serving-6"
      - "serving-7"
      - "serving-8"
      - "serving-9"
      - "serving-10"
      - "serving-11"
      - "serving-12"
      - "serving-13"
      - "serving-14"
      - "serving-15"
      - "serving-16"
      - "serving-17"
      - "serving-18"
      - "serving-19"
      - "serving-20"
      - "serving-21"
      - "serving-22"
      - "serving-23"
      - "serving-24"
      - "serving-25"
      - "serving-26"
      - "serving-27"
      - "serving-28"
      - "serving-29"
      - "serving-30"
      - "serving-31"
      - "serving-32"
      - "serving-33"
      - "serving-34"
      - "serving-35"
      - "serving-36"
      - "serving-37"
      - "serving-38"
      - "serving-39"
      - "serving-40"
      - "serving-41"
      - "serving-42"
      - "serving-43"
      - "serving-44"
      - "serving-45"
      - "serving-46"
      - "serving-47"
      - "serving-48"
      - "serving-49"
      - "serving-50"
      - "serving-51"
      - "serving-52"
      - "serving-53"
      - "serving-54"
      - "serving-55"
      - "serving-56"
      - "serving-57"
      - "serving-58"
      - "serving-59"
      - "serving-60"
      - "serving-61"
      - "serving-62"
      - "serving-63"
      - "serving-64"
      - "serving-65"
      - "serving-66"
      - "serving-67"
      - "serving-68"
      - "serving-69"
      - "serving-70"
      - "serving-71"
      - "serving-72"
      - "serving-73"
      - "serving-74"
      - "serving-75"
      - "serving-76"
      - "serving-77"
      - "serving-78"
      - "serving-79"
      - "serving-80"
    - key: hypershift.openshift.io/request-serving-component
      operator: In
      values:
      - "true"
  unhealthyConditions:
  # Neither NonexistentStatus nor NonexistentCondition really exist as status conditions on a node.
  # This lets the MachineHealthCheck only trigger when a node is deleted and not on any other node
  # status conditions.
  # # https://github.com/openshift/machine-api-operator/blob/c11d6227cb4640ce979edd4e9469342274e88910/pkg/controller/machinehealthcheck/machinehealthcheck_controller.go#L789-L793
  - status: "NonexistentStatus"
    type: "NonexistentCondition"
    timeout: "0s"
  maxUnhealthy: 100%
  nodeStartupTimeout: 25m
