apiVersion: machine.openshift.io/v1beta1
kind: MachineHealthCheck
metadata:
  name: srep-management-cluster-node-recovery
  namespace: openshift-machine-api
spec:
  selector:
    matchExpressions:
    - key: machine.openshift.io/cluster-api-machine-role
      operator: NotIn
      values:
      - "infra"
      - "master"
    - key: hypershift.openshift.io/request-serving-component
      operator: In
      values:
      - "true"
  unhealthyConditions:
  # Neither NonexistentStatus nor NonexistentCondition really exist as status conditions on a node.
  # This lets the MachineHealthCheck only trigger when a node is deleted and not on any other node
  # status conditions.
  # # https://github.com/openshift/machine-api-operator/blob/c11d6227cb4640ce979edd4e9469342274e88910/pkg/controller/machinehealthcheck/machinehealthcheck_controller.go#L789-L793
  - status: "NonexistentStatus"
    type: "NonexistentCondition"
    timeout: "0s"
  maxUnhealthy: 100%
  nodeStartupTimeout: 25m
