apiVersion: machine.openshift.io/v1beta1
kind: MachineHealthCheck
metadata:
  name: srep-management-cluster-node-recovery
  namespace: openshift-machine-api
spec:
  selector:
    matchExpressions:
    - key: machine.openshift.io/cluster-api-machine-role
      operator: NotIn
      values:
      - "infra"
      - "master"
    - key: hypershift.openshift.io/request-serving-component
      operator: In
      values:
      - "true"
  unhealthyConditions:
  - type:    "Ready"
    timeout: "480s"
    status: "Unknown"
  maxUnhealthy: 100%
  nodeStartupTimeout: 25m
