apiVersion: machine.openshift.io/v1beta1
kind: MachineHealthCheck
metadata:
  name: srep-management-cluster-node-recovery
  namespace: openshift-machine-api
spec:
  selector:
    matchExpressions:
    - key: machine.openshift.io/cluster-api-machine-role
      operator: NotIn
      values:
      - "infra"
      - "master"
    - key: hypershift.openshift.io/request-serving-component
      values:
      - "true"
  # An empty unhealthyConditions causes this MHC to execute only if a machine's underlying node is deleted
  # https://github.com/openshift/machine-api-operator/blob/c11d6227cb4640ce979edd4e9469342274e88910/pkg/controller/machinehealthcheck/machinehealthcheck_controller.go#L789-L793
  unhealthyConditions: []
  maxUnhealthy: 100%
  nodeStartupTimeout: 25m
