apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: scanner
  namespace: openshift-scanning
spec:
  selector:
    matchLabels:
      name: scanner
  template:
    metadata:
      labels:
        name: scanner
    spec:
      containers:
      - env:
        - name: OO_PAUSE_ON_START
          value: "false"
        - name: CLAM_DB_DIRECTORY
          value: "/clam"
        - name: DEBUG_SECRETS
          value: "false"
        - name: CLAM_SECRETS_FILE
          value: "/secrets/clam_update_config.json"
        - name: OPENSSL_FORCE_FIPS_MODE
          value: "1"
        image: quay.io/app-sre/clamsig-puller@sha256:4830b1ff47d92f1d485115724d8a06e50d99802fcba968154a02e1085f123d53
        name: clamsig-puller
        resources:
          limits:
            cpu: 100m
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 500Mi
        volumeMounts:
        - mountPath: /secrets
          name: clam-secrets
        - mountPath: /clam
          name: clam-files
      - env:
        - name: OO_PAUSE_ON_START
          value: "false"
        - name: OPENSSL_FORCE_FIPS_MODE
          value: "1"
        image: quay.io/app-sre/clamd@sha256:aa5fbc941535c8c5dbd55e32eaadb73be894fab116da32e1a64c080f77ef1dd1
        name: clamd
        resources:
          limits:
            cpu: 300m
            memory: 3Gi
          requests:
            cpu: 100m
            memory: 800Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - mountPath: /var/lib/clamav
          name: clam-files
      - env:
        - name: OO_PAUSE_ON_START
          value: "false"
        - name: CHROOT_PATH
          value: /host
        - name: OPENSSL_FORCE_FIPS_MODE
          value: "1"
        image: quay.io/app-sre/container-info@sha256:aa5fbc941535c8c5dbd55e32eaadb73be894fab116da32e1a64c080f77ef1dd1
        name: info
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 20Mi
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
        - mountPath: /clam
          name: clam-files
        - mountPath: /host
          name: host-filesystem
      - env:
        - name: OO_PAUSE_ON_START
          value: "false"
        - name: ACTIVE_SCAN
          value: "true"
        - name: CRIO_LOG_URL
          value: https://loggerservice.openshift-scanning.svc.cluster.local:8443/api/crio/log
        - name: DOCKER_LOG_URL
          value: https://loggerservice.openshift-scanning.svc.cluster.local:8443/api/docker/log
        - name: CLAM_LOG_URL
          value: https://loggerservice.openshift-scanning.svc.cluster.local:8443/api/clam/scanresult
        - name: JOURNAL_PATH
          value: /var/log/journal
        - name: SCAN_RESULTS_DIR
        - name: POST_RESULT_URL
          value: https://loggerservice.openshift-scanning.svc.cluster.local:8443/api/clam/scanresult
        - name: OUT_FILE
        - name: SKIP_NAMESPACE_PREFIXES
          value: openshift-
        - name: SKIP_NAMESPACES
          value: openshift-scanning,ci
        - name: CLAM_SOCKET
          value: /clam/clamd.sock
        - name: INFO_SOCKET
          value: '@rpc.sock'
        - name: OPENSSL_FORCE_FIPS_MODE
          value: "1"
        image: quay.io/app-sre/watcher@sha256:8fa6eca92a2fbd1c6b14aee8472a509ea14cae68b69390d0811532e57fc509fd
        name: watcher
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
        - mountPath: /secrets
          name: clam-secrets
        - mountPath: /var/log/journal
          name: watcher-host-journal
        - mountPath: /host
          name: host-filesystem
        - mountPath: /clam
          name: clam-files
      - env:
        - name: OO_PAUSE_ON_START
          value: "false"
        - name: CRIO_LOG_URL
          value: https://loggerservice.openshift-scanning.svc.cluster.local:8443/api/crio/log
        - name: DOCKER_LOG_URL
          value: https://loggerservice.openshift-scanning.svc.cluster.local:8443/api/docker/log
        - name: CLAM_LOG_URL
          value: https://loggerservice.openshift-scanning.svc.cluster.local:8443/api/clam/scanresult
        - name: JOURNAL_PATH
          value: /var/log/journal
        - name: SCAN_RESULTS_DIR
        - name: POST_RESULT_URL
          value: https://loggerservice.openshift-scanning.svc.cluster.local:8443/api/clam/scanresult
        - name: OUT_FILE
        - name: CLAM_SOCKET
          value: /clam/clamd.sock
        - name: INFO_SOCKET
          value: '@rpc.sock'
        - name: SCHEDULED_SCAN
          value: "true"
        - name: SCHEDULED_SCAN_DAY
          value: Saturday
        - name: MIN_CON_DAY
          value: "0"
        - name: SKIP_NAMESPACE_PREFIXES
          value: openshift-
        - name: SKIP_NAMESPACES
          value: openshift-scanning
        - name: HOST_SCAN_DIRS
          value: /host
        - name: OPENSSL_FORCE_FIPS_MODE
          value: "1"
        image: quay.io/app-sre/watcher@sha256:8fa6eca92a2fbd1c6b14aee8472a509ea14cae68b69390d0811532e57fc509fd
        name: scheduler
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
        - mountPath: /var/log/journal
          name: watcher-host-journal
        - mountPath: /host
          name: host-filesystem
        - mountPath: /clam
          name: clam-files
      dnsPolicy: ClusterFirst
      initContainers:
      - env:
        - name: OO_PAUSE_ON_START
          value: "false"
        - name: INIT_CONTAINER
          value: "true"
        - name: CLAM_DB_DIRECTORY
          value: "/clam"
        - name: DEBUG_SECRETS
          value: "false"
        - name: CLAM_SECRETS_FILE
          value: "/secrets/clam_update_config.json"
        - name: OPENSSL_FORCE_FIPS_MODE
          value: "1"
        image: quay.io/app-sre/clamsig-puller@sha256:4830b1ff47d92f1d485115724d8a06e50d99802fcba968154a02e1085f123d53
        name: init-clamsig-puller
        resources:
          limits:
            cpu: 100m
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 50Mi
        volumeMounts:
        - mountPath: /secrets
          name: clam-secrets
        - mountPath: /clam
          name: clam-files
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: scanner-sa
      tolerations:
      - operator: Exists
      volumes:
      - name: clam-secrets
        secret:
          secretName: clam-secrets
      - emptyDir: {}
        name: clam-files
      - hostPath:
          path: /
          type: ""
        name: host-filesystem
      - hostPath:
          path: /var/log/journal
          type: ""
        name: watcher-host-journal
