apiVersion: v1
kind: Secret
metadata:
  name: support
  namespace: openshift-config
type: Opaque
data:
  endpoint: aHR0cHM6Ly9jbG91ZC5zdGFnZS5yZWRoYXQuY29tL2FwaS9pbmdyZXNzL3YxL3VwbG9hZA==
  reportEndpoint: aHR0cHM6Ly9jbG91ZC5zdGFnZS5yZWRoYXQuY29tL2FwaS9pbnNpZ2h0cy1yZXN1bHRzLWFnZ3JlZ2F0b3IvdjEvY2x1c3RlcnMvJXMvcmVwb3J0
  scaEndpoint: aHR0cHM6Ly9hcGkuc3RhZ2Uub3BlbnNoaWZ0LmNvbS9hcGkvYWNjb3VudHNfbWdtdC92MS9jZXJ0aWZpY2F0ZXM=
