apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 00-worker-chrony
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
        - contents:
            compression: gzip
            source: data:;base64,H4sIAAAAAAAC/5zL3U7DMAzF8fs8hZ8gWVoo7HEyzylW8yXbm9jbI0oRXCLujs5fPyW5k0Cczn7x8dlPrzCEMgnw5SZqULmNXgo8QU3vX8t9o3nycZn9+cXHf6jlT+oqnC1zIQj3JKHwJeCb9PYIe3FiqI+GrqaN1GhAPJ1gdqWvV5bD9PUwnzeYJNy4rVAp6U2oUjPdy+8D1JKxGqP+CDEEoYyl46ZgVAf2OtxHAAAA//8q3ru0RQEAAA==
          mode: 420
          overwrite: true
          path: /etc/chrony.conf