apiVersion: v1
kind: ServiceAccount
metadata:
  name: osd-delete-backplane-remediation-rbacs
  namespace: openshift-backplane
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: osd-delete-backplane-remediation-rbacs
rules:
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
      - rolebindings
      - clusterroles
      - clusterrolebindings
    verbs:
      - get
      - list
      - delete
