apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: osd-delete-backplane-remediation-rbacs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: osd-delete-backplane-remediation-rbacs
subjects:
  - kind: ServiceAccount
    name: osd-delete-backplane-remediation-rbacs
    namespace: openshift-backplane
