apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: sre-managed-notification-alerts-for-customer-webhooks
    role: alert-rules
  name: sre-managed-notification-alerts-for-customer-webhooks
  namespace: openshift-monitoring
spec:
  groups:
  - name: customer-webhooks
    rules:
    - alert: SlowCustomerWebhookSRE
      expr: |-
        (
          label_replace(
            label_replace(
              increase(apiserver_admission_webhook_admission_duration_seconds_sum[5m]) /
                increase(apiserver_admission_webhook_admission_duration_seconds_count[5m]),
            "type", "mutating", "type", "admit"),
          "webhook_name", "$0", "name", ".*")
        ) * on(webhook_name) group_left(service_namespace, service_name) (
          kube_validatingwebhookconfiguration_webhook_clientconfig_service{service_namespace !~ "openshift-.*"} or on(webhook_name)
          kube_mutatingwebhookconfiguration_webhook_clientconfig_service{service_namespace !~ "openshift-.*"}
        ) > 1
      for: 15m
      labels:
        severity: warning
        send_managed_notification: "true"
        managed_notification_template: "SlowCustomerWebhook"
        duration_threshold: "1 second"
      annotations:
        summary: Customer defined admission webhook is slow.
        description: "{{ $labels.webhook_name }} webhook is slow on {{ $labels.operation }} operations"
