apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: sre-managed-notification-alerts
    role: alert-rules 
  name: sre-managed-notification-alerts
  namespace: openshift-monitoring
spec:
  groups:
  - name: sre-managed-notification-alerts
    rules:
    - alert: LoggingVolumeFillingUpNotificationSRE
    # KubePersistentVolumeFillingUp alert firing in openshift-logging Namespace.
      expr: count(ALERTS{alertname="KubePersistentVolumeFillingUp", alertstate="firing", namespace="openshift-logging"}) >= 1
      for: 30m
      labels:
        severity: Info
        namespace: openshift-logging
        send_managed_notification: "true"
        managed_notification_template: "LoggingVolumeFillingUp"
    - alert: ElasticsearchNodeDiskWatermarkReachedSRE
      expr: count(ALERTS{alertname="ElasticsearchNodeDiskWatermarkReached", alertstate="firing", namespace="openshift-logging", severity="critical"}) >= 1
      for: 30m
      labels:
        severity: Info
        namespace: openshift-logging
        send_managed_notification: "true"
        managed_notification_template: "ElasticsearchNodeDiskWatermarkReached"
    - alert: ElasticsearchDiskSpaceRunningLowSRE
      expr: count(ALERTS{alertname="ElasticsearchDiskSpaceRunningLow", alertstate="firing", namespace="openshift-logging"}) >= 1
      for: 30m
      labels:
        severity: Info
        namespace: openshift-logging
        send_managed_notification: "true"
        managed_notification_template: "ElasticsearchDiskSpaceRunningLow"
    - alert: ElasticsearchClusterNotHealthySRE
      expr: count(ALERTS{alertname="ElasticsearchClusterNotHealthy", alertstate="firing", namespace="openshift-logging", severity="critical"}) >= 1
      for: 10m
      labels:
        severity: Info
        namespace: openshift-logging
        send_managed_notification: "true"
        managed_notification_template: "ElasticsearchClusterNotHealthy"