apiVersion: managed.openshift.io/v1alpha1
kind: SubjectPermission
metadata:
  name: backplane-rhoam-lpsre-admins
  namespace: openshift-rbac-permissions
spec:
  permissions:
  - allowFirst: true
    clusterRoleName: backplane-rhoam-lpsre-admins-project
    namespacesAllowedRegex: (^redhat-rhoami?$|^redhat-rhoami?-.*)
  - allowFirst: true
    clusterRoleName: view
    namespacesAllowedRegex: (^redhat-rhoami?$|^redhat-rhoami?-.*)
  subjectKind: Group
  subjectName: system:serviceaccounts:openshift-backplane-lpsre
