apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: osd-custom-domains-dedicated-admin-cluster
rules:
- apiGroups:
  - managed.openshift.io
  resources:
  - customdomains
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
