aggregationRule:
  clusterRoleSelectors:
  # aggregate all "cluster" scope rbac from SRE to dedicated-admins-cluster
  - matchExpressions:
    - key: managed.openshift.io/aggregate-to-dedicated-admins
      operator: In
      values:
        - "cluster"
  # aggregate all customer installed operator rbac from OLM to dedicated-admins-cluster (pre 4.3.12)
  - matchExpressions:
    - key: olm.opgroup.permissions/aggregate-to-admin
      operator: In
      values:
        - openshift-logging
        - openshift-operators
        - openshift-operators-redhat
  # aggregate all customer installed operator rbac from OLM to dedicated-admins-cluster (4.3.12+)
  - matchExpressions:
    - key: olm.owner.kind
      operator: In
      values:
      - OperatorGroup
    - key: olm.owner.namespace
      operator: NotIn
      values:
      - openshift-cloud-ingress-operator
      - openshift-monitoring
      - openshift-operator-lifecycle-manager
      - openshift-rbac-permissions
      - openshift-splunk-forwarder-operator
      - openshift-velero
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dedicated-admins-cluster
rules: []