aggregationRule:
  clusterRoleSelectors:
  # aggregate all "cluster" scope rbac from SRE to dedicated-admins-cluster
  - matchExpressions:
    - key: managed.openshift.io/aggregate-to-dedicated-admins
      operator: In
      values:
        - "cluster"
  # aggregate all customer installed operator rbac from OLM to dedicated-admins-cluster
  - matchExpressions:
    - key: olm.opgroup.permissions/aggregate-to-admin
      operator: In
      values:
        - openshift-logging
        - openshift-operators
        - openshift-operators-redhat
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dedicated-admins-cluster
rules: []