apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dedicated-admins-openshift-logging
  namespace: openshift-logging
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - "*"
