---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hs-delete-custom-cmo-config
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  resourceNames:
  - "ext-cluster-monitoring-operator-config"
  verbs:
  - "*"
