aggregationRule:
  clusterRoleSelectors:
    # aggregate all "view" scope rbac
    - matchExpressions:
        - key: rbac.authorization.k8s.io/aggregate-to-view
          operator: In
          values:
            - "true"
    - matchExpressions:
        - key: managed.openshift.io/aggregate-to-backplane-csm
          operator: In
          values:
            - "true"
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backplane-csm-readers-cluster
rules: []