apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rhods-prometheus-viewer
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: redhat-ods-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-monitoring-view 
