deploymentMode: "SelectorSyncSet"
selectorSyncSet:
  matchExpressions:
    - key: api.openshift.com/id
      operator: In
      values: "${{ROUTER_REPLICA_CLUSTER_IDS}}"
    - key: api.openshift.com/fedramp
      operator: NotIn
      values: ["true"]           
