deploymentMode: "SelectorSyncSet"
selectorSyncSet:
  matchExpressions:
    - key: api.openshift.com/fedramp
      operator: In
      values:
        - "true"
    - key: hive-prod01
      operator: In
      values:
      - "true"            
  resourceApplyMode: Upsert
