apiVersion: v1
kind: Namespace
metadata:
  name: openshift-customer-monitoring
  annotations:
    openshift.io/node-selector: ""
  labels:
    openshift.io/cluster-logging: "true"
    openshift.io/cluster-monitoring: "false"
