apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: ClusterLogging.v1.logging.openshift.io
  name: openshift-customer-monitoring
  namespace: openshift-customer-monitoring
spec:
  serviceAccount:
    metadata:
      creationTimestamp: null
  targetNamespaces:
  - openshift-customer-monitoring
