apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dedicated-admins-openshift-customer-monitoring
  namespace: openshift-customer-monitoring
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  - pods/log
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - operators.coreos.com
  resources:
  - subscriptions
  - clusterserviceversions
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - secrets
  resourceNames:
  - alertmanager-main
  - alertmanager-main-proxy
  verbs:
  - "*"
- apiGroups:
  - "monitoring.coreos.com"
  resources:
  - prometheuses
  - alertmanagers
  - prometheusrules
  - servicemonitors
  - podmonitors
  verbs:
  - "*"