---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ocpbugs-20184
  namespace: openshift-network-node-identity
spec:
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 2
  concurrencyPolicy: Replace
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 3600
      template:
        metadata:
          labels:
            app: ocpbugs-20184
        spec:
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - preference:
                  matchExpressions:
                  - key: node-role.kubernetes.io/infra
                    operator: Exists
                weight: 1
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                    - key: app
                      operator: In
                      values:
                      - ocpbugs-20184
                  topologyKey: kubernetes.io/hostname
                weight: 1
          tolerations:
            - effect: NoSchedule
              operator: Exists
          serviceAccountName: ocpbugs-20184
          restartPolicy: Never
          containers:
          - name: ocpbugs-20184
            image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
            imagePullPolicy: Always
            resources:
              requests:
                cpu: 100m
                memory: 100Mi
              limits:
                cpu: 100m
                memory: 100Mi
            command:
            - oc
            - delete
            - pods
            - --namespace=openshift-network-node-identity
            - --selector=app=network-node-identity
            - --wait=false
            - --ignore-not-found
            - --grace-period=1
