---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ocpbugs-20184
  namespace: openshift-network-node-identity
spec:
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 3
  concurrencyPolicy: Replace
  schedule: "22 * * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 3600
      template:
        spec:
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - preference:
                  matchExpressions:
                  - key: node-role.kubernetes.io/infra
                    operator: Exists
                weight: 1
          tolerations:
            - effect: NoSchedule
              key: node-role.kubernetes.io/infra
              operator: Exists
          serviceAccountName: ocpbugs-20184
          restartPolicy: Never
          containers:
          - name: ocpbugs-20184
            image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
            imagePullPolicy: Always
            command:
            - oc
            - delete
            - pods
            - --namespace=openshift-network-node-identity
            - --selector=app=network-node-identity
            - --wait=false
            - --ignore-not-found
            - --grace-period=1
