deploymentMode: "SelectorSyncSet"
selectorSyncSet:
  resourceApplyMode: Sync
  matchExpressions:
  - key: hive.openshift.io/version
    operator: In
    values: ["4.14.0-rc.3", "4.14.0-rc.4", "4.15.0-ec.0"]
