name: Make Generate
on:
  push:
    branches-ignore:
      - master

jobs:
  run:
    name: Make Generate Template
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Make
      run: make

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        message: "on push: make"
        add: "hack/00-osd-managed-cluster-config*.yaml.tmpl"
