apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dedicated-admins-project-request
  namespace: openshift-config
rules:
- apiGroups:
  - template.openshift.io
  resources:
  - templates
  resourceNames:
  - project-request
  verbs:
  - create
  - get
  - patch
  - update
  - watch
